azure:
  timeout_minutes: 600
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
# idle_timeout_minutes: 90
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: azure
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
upload_on_branch: windows_fix_upload
